### ISSUE TITLE
Reading version from `.ruby-version` and Windows support

### ISSUE THREAD

**Issue by gencer** [eregon/use-ruby-action#4]
What is the best way of reading ruby version from `.ruby-version` file?

Something like:

```yaml
      - uses: eregon/use-ruby-action@master
        with:
          ruby-version: "$(cat .ruby-version)" # or similar
```

<s>Also, I didn't want to open an another issue for this but do you plan to support Windows? It would be awesome if we can get the windows builds.</s> Windows support is live. Thank you.

**Comment by eregon** [comment]
Unfortunately I think that syntax doesn't work and GitHub Actions is fairly restrictive on values for `with:`.
Did you try it to see what happens? I guess the String is passed as-is.

Maybe I should add a special value like `".ruby-version"`, or I think simpler if `ruby-version:` is unset look if there is a `.ruby-version` in the current directory and use that?

**Comment by gencer** [comment]
For the first question, as you presumed it didn't worked.

And for `.ruby-version` support will be awesome because, we constantly update our ruby versions and it will be great to see it sync on each CI runs. This way, dependabot and other pull requests that uses another version (outdated) will still work even if we upgrade on `master`.

**Comment by eregon** [comment]
Could you give me an example of the format you use for `.ruby-version`?
Something like `ruby-2.6.5`?

**Comment by eregon** [comment]
It works with a61be15bffe8c2671699ce4b4eb6e7c8f2ce3f4d, thank you for the suggestion.
I updated the README to document this.

Using
```yaml
    - uses: eregon/use-ruby-action@master
```
should be enough if there is a `.ruby-version` file.

You can also set it explicitly to `.ruby-version`:
```yaml
    - uses: eregon/use-ruby-action@master
      with:
        ruby-version: .ruby-version
```
