### ISSUE TITLE
Bundler cache mechanism not as efficient as with setup-rbenv method

### ISSUE THREAD

**Issue by vvo** [eregon/use-ruby-action#7]
Hi there, I was previously using https://github.com/masa-iwasaki/setup-rbenv from @masa-iwasaki and the bundler cache method from: https://github.com/actions/cache/blob/master/examples.md#ruby---gem

After switching to use-ruby-action then the bundler cache seems to never be read.

Here's my full workflow: https://gist.github.com/vvo/5f7b8a1d34d5efc2df18140fb1d3ed20

Bundle install always takes multiple minutes while previously it was taking 10s. Any idea what could be wrong?

**Comment by eregon** [comment]
Thank you for the report! That's definitely unexpected, the cache action should work fine with any other action to setup Ruby.
Maybe different Bundler versions have some effect.

Do you happen to have a log showing it doesn't work?

I'll try to reproduce on the given workflow or a simplified version of it.

**Comment by eregon** [comment]
One issue is the Ruby version needs to be taken into account if using multiple Ruby versions, otherwise it shows:
https://github.com/eregon/mspec/runs/381174118
```
Post actions/cache@v1 0s
[warning]Cache already exists. Scope: refs/heads/try-bundler-caching, Key: Linux-gem-326998accfb49e7bde26a0421ef825a0d07a38032fd3b1ba97e81941957c2988, Version: (null)
```

**Comment by eregon** [comment]
It works for this simple example:
```yaml
name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.4.9', '2.5.7', '2.6.5', '2.7.0', 'truffleruby' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eregon/use-ruby-action@master
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-${{ matrix.ruby }}-
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - run: bundle exec rspec

```
https://github.com/eregon/mspec/runs/381183043
